In [ ]:
!pip install -q -U transformers accelerate datasets peft evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 108.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 73.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 62.4 MB/s eta 0:00:00

In [ ]:
!pip uninstall -y transformers
!pip install --no-cache-dir transformers==4.45.0

Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Collecting transformers==4.45.0
  Downloading transformers-4.45.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (3.25.2)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.45.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (2.32.4)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.45.0)
  Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.45.0) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.0) (1.4.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.45.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.45.0) (2026.2.25)
Downloading transformers-4.45.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 72.7 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 913.2 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 227.7 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.7.1
    Uninstalling huggingface_hub-1.7.1:
      Successfully uninstalled huggingface_hub-1.7.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
Successfully installed huggingface-hub-0.36.2 tokenizers-0.20.3 transformers-4.45.0

In [ ]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes) (1.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 41.5 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.2

## Dataset

In [ ]:
from datasets import load_dataset

ds_nli = load_dataset("nala-cub/americas_nli", "hch")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

hch/validation-00000-of-00001.parquet:   0%|          | 0.00/46.7k [00:00<?, ?B/s]

hch/test-00000-of-00001.parquet:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

Generating validation split:   0%|          | 0/743 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/750 [00:00<?, ? examples/s]

In [ ]:
ds_nli

DatasetDict({
    validation: Dataset({
        features: ['premise', 'hypothesis', 'label'],
        num_rows: 743
    })
    test: Dataset({
        features: ['premise', 'hypothesis', 'label'],
        num_rows: 750
    })
})

In [ ]:
ds_nli['test'][0]

{'premise': 'mu hekwa.',
 'hypothesis': 'neuka tita xatawe m+k+ mat+a.',
 'label': 2}

In [ ]:
import pandas as pd
path = "/content/drive/MyDrive/AmericasNLP-2026/multilingual_translation_model/data/concat_all_dev_train.csv"
df_translation= pd.read_csv(path)
df_translation = df_translation[df_translation['lang-pair']=='wixarika-spanish']
df_translation

,lang-pair,split,source,target
35531,wixarika-spanish,dev,Y en realidad no lo entendió.,yemek+ p+kei ti eniet+ya.
35532,wixarika-spanish,dev,Necesito más información para decidir qué tipo...,nepeuye h+wa wa+ka iwaurika m+k+ nem+ta y+n+ k...
35533,wixarika-spanish,dev,Era una selva tropical.,pe h+k+t+kai metsi+ra+ ye tsie nieka ti+x+kat+.
35534,wixarika-spanish,dev,"Además, tiene la satisfacción de saber que sus...","heimana rieka, pexeiya ik+ m+tema wi+r+k+ ment..."
35535,wixarika-spanish,dev,"Concretamente, te unirás a un grupo de disting...","tse ´i mek+, peuwat+n+ní hipame y+k+ me anenem..."
...,...,...,...,...
45486,wixarika-spanish,train,Les dijo entonces el rey:,kuit+ tiwareta h+awix+ rey:
45487,wixarika-spanish,train,Ve inmediatamente.,kenemie xeimieme.
45488,wixarika-spanish,train,y él fue convertido en piedra.,m+k+ payeit+arie tete.
45489,wixarika-spanish,train,éste es un niño,'ik+ p+nunutsi
45490,wixarika-spanish,train,"-""Oh, reina,","""oh, reina,"

In [ ]:
path = "/content/drive/MyDrive/AmericasNLP-2026/vlm_experiments/LM_vLM/ss-corpus-hch.tsv"
df_voice= pd.read_csv(path, sep='\t')
df_voice

,client_id,audio_id,audio_file,duration_ms,prompt_id,prompt,transcription,votes,age,gender,accents,variant,language,prompt_upvotes,prompt_reports,is_edited,split,char_per_sec,quality_tags
0,3f5e9fbee3aa69948976d168693797f5,20341,spontaneous-speech-hch-20341.mp3,8136,2701,¿Taniuki mɨkaheuyewautsenikɨ ke teʼaneni?,Ne tsɨ netinekuʼeriwa kename teʼutiniukani tan...,1,NaN,NaN,NaN,NaN,Wixárika,0,0,1,dev,7.989184,non-allowed-script|mixed-script-words
1,2d09dcea66332097e98138499b0aebec,28807,spontaneous-speech-hch-28807.mp3,40392,2707,¿Ke peyɨanetɨ ‘uximaayatsika pepukaxei?,"Ne ʼuuximayátsika nepunetiʼɨkitɨa ʼiimayarikɨ,...",1,NaN,NaN,NaN,NaN,Wixárika,0,0,1,train,10.026738,non-allowed-script|mixed-script-words
2,2d09dcea66332097e98138499b0aebec,28808,spontaneous-speech-hch-28808.mp3,39276,2702,¿Pemɨretituayatsie yátɨni pemɨrewaʼuximaayá pe...,"Hiikɨ ri maatsi tsitiuyɨtɨkaitɨ́ pɨtixuawe, mɨ...",1,NaN,NaN,NaN,NaN,Wixárika,0,0,1,train,10.158876,non-allowed-script|mixed-script-words
3,2d09dcea66332097e98138499b0aebec,28809,spontaneous-speech-hch-28809.mp3,49896,2713,¿Ke tiyɨanekaku teiwari niukieya matɨari pepuʼ...,Tsɨ rikɨ méripai tɨ temɨkawaxexeiyákai teiwari...,1,NaN,NaN,NaN,NaN,Wixárika,0,0,1,train,10.121052,mixed-script-words|non-allowed-script
4,2d09dcea66332097e98138499b0aebec,28810,spontaneous-speech-hch-28810.mp3,21564,2709,¿Matɨari mawiwe pemuxeitsie ke petiyurienekai?,Méripai tɨ mawiiwe nemuxeitsie rikɨ ne escuela...,1,NaN,NaN,NaN,NaN,Wixárika,0,0,1,train,8.347245,non-allowed-script|mixed-script-words
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,6a057806fe632fc4cf361fa195d4a982,45535,spontaneous-speech-hch-45535.mp3,19692,4583,¿Pemɨʼiwatsiekatsie tita ʼikwaiyari pemɨrakuwe...,Xɨka xewítɨ netsi'iwaatáni mɨɨkɨ pɨnetsinake '...,1,twenties,female_feminine,NaN,NaN,Wixárika,0,0,1,test,7.566524,non-allowed-script|mixed-script-words
1549,6a057806fe632fc4cf361fa195d4a982,45536,spontaneous-speech-hch-45536.mp3,19980,4530,¿ʼImatɨrieka ke petiyurienetɨ tixaɨtɨ pepɨtiut...,"Mɨɨkɨ neheku'iwaatáka, xeíme neheku'iwaatáka n...",1,twenties,female_feminine,NaN,NaN,Wixárika,0,0,1,test,7.557558,non-allowed-script|mixed-script-words
1550,6a057806fe632fc4cf361fa195d4a982,45537,spontaneous-speech-hch-45537.mp3,24156,4543,¿Ke petikuʼeriwa titayari hípatɨ wiixáritari ʼ...,Ta'iwaáma hipátɨ yuwaɨkawa 'anutaɨye meme'uuwa...,1,twenties,female_feminine,NaN,NaN,Wixárika,0,0,1,test,8.031131,mixed-script-words|non-allowed-script
1551,6a057806fe632fc4cf361fa195d4a982,45538,spontaneous-speech-hch-45538.mp3,23940,4493,¿ʼAteukari ke tiumaika matsiʼukateukaritaxɨ?,Mɨɨkɨ neteukari me... mepɨnetsi'ukateukaritaxɨ...,1,twenties,female_feminine,NaN,NaN,Wixárika,0,0,1,test,6.975773,NaN
1552,6a057806fe632fc4cf361fa195d4a982,45539,spontaneous-speech-hch-45539.mp3,15804,2709,¿Matɨari mawiwe pemuxeitsie ke petiyurienekai?,Maatɨari nemixeitsíe mawiiwe mɨɨkɨ maana newai...,1,twenties,female_feminine,NaN,NaN,Wixárika,0,0,1,test,7.403189,NaN

In [ ]:
all_txt = []

def extract_samples(data):
  samples = []
  for item in data:
    samples.append(item['premise'])
    samples.append(item['hypothesis'])
  return samples

all_txt = extract_samples(ds_nli['validation'])
all_txt.extend(extract_samples(ds_nli['test']))

In [ ]:
len(all_txt)

2986

In [ ]:
all_txt.extend([sentence for sentence in df_translation['target']])
all_txt.extend([sentence for sentence in df_voice['transcription']])

In [ ]:
len(all_txt)

14499

In [ ]:
filter_ = list(set(all_txt))
filter_ = [item for item in filter_ if len(str(item).split()) >3]
len(filter_)

10936

In [ ]:
#save
from datasets import Dataset

path = "/content/drive/MyDrive/AmericasNLP-2026/vlm_experiments/LM_vLM/"
# Create a Dataset object
hf_dataset = Dataset.from_dict({'text':filter_})
hf_dataset.save_to_disk(path+"wixarika_monolingual")

print(hf_dataset)

Saving the dataset (0/1 shards):   0%|          | 0/10936 [00:00<?, ? examples/s]

Dataset({
    features: ['text'],
    num_rows: 10936
})

## Continued Pre-Training

In [ ]:
import torch
from datasets import load_dataset, concatenate_datasets
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model

In [ ]:
from datasets import load_from_disk, concatenate_datasets, load_dataset

english_subset_size = 500  # Number of English samples to mix in
path = "/content/drive/MyDrive/AmericasNLP-2026/vlm_experiments/LM_vLM/"


# Load your language
local_ds = load_from_disk(path+"wixarika_monolingual")

# Load a small slice of English (Wiki) to prevent catastrophic forgetting
en_ds = load_dataset("wikimedia/wikipedia", "20231101.en", split="train", streaming=True)
en_ds_list = []
for i, entry in enumerate(en_ds):
    if i >= english_subset_size: break
    en_ds_list.append({"text": entry["text"]})

from datasets import Dataset
en_ds_final = Dataset.from_list(en_ds_list)

# Combine and shuffle
combined_ds = concatenate_datasets([local_ds, en_ds_final]).shuffle(seed=42)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

In [ ]:
# 1. SETTINGS
model_id = "google/gemma-2b"
output_dir = path+"gemma-2b-wixarika"

In [ ]:
from huggingface_hub import login
login(token="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")
# 2. TOKENIZER & DATA MIXING
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_fn(examples):
    return tokenizer(examples["text"], truncation=True, max_length=512)

tokenized_ds = combined_ds.map(tokenize_fn, batched=True, remove_columns=["text"])

In [ ]:
# 3. LOAD MODEL (Bfloat16 for stability)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

# 4. LORA SETUP
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
# 5. TRAINING
args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=3, # Usually 1-3 epochs for CPT
    bf16=True,
    logging_steps=500,
    save_total_limit=2,
    optim="paged_adamw_8bit"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized_ds,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

trainer.train()

# 6. SAVE & MERGE (Crucial for the PaliGemma swap)
print("Merging LoRA weights into base model...")
merged_model = model.merge_and_unload()
merged_model.save_pretrained(f"{output_dir}-merged")
tokenizer.save_pretrained(f"{output_dir}-merged")

print(f"Success! Specialized LM is ready at {output_dir}-merged")

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Merging LoRA weights into base model...
Success! Specialized LM is ready at /content/drive/MyDrive/AmericasNLP-2026/vlm_experiments/LM_vLM/gemma-2b-wixarika-merged